### ISSUE TITLE
Explanations in Readme

### ISSUE THREAD

**Issue by agriffard** [Skrypt/OrchardCore.Samples#5]
A few remarks about the Readme:

- `dotnet new --debug:reinit` is only to use if you want to reinitialize the templates available in `dotnet new`.
- If you use `dotnet new ocmodule` with `-PartName "TestPart" `, you should always use it with `-AddPart true` for the moment.
- Please, try to explain what the commands option are doing when you use `dotnet new`.
- When you explain how to create a new CMS project and add new module or theme, you should do it starting from another empty solution, not from the OrchardCore.Templates one, or it is confusing.
- In the future, we will publsih the nuget corresponding to the Templates and people will be able to install them by executing  `dotnet new -i "TheNugetNameWeChooseForOCTemplates"`
- I don't know why you talk about Orchardcore-dev on MyGet, that is off-topic.

**Comment by Skrypt** [comment]
I fixed the dotnet new --debug:reinit explanation. The reason why I'm talking about Orchardcore-dev is mainly because I'm trying to write a documentation that could be used for both source code and this solution. I will reuse this readme for Orchard Core documentation on how to create a module. It will require to redo the images and maybe adapt some text here and there. For the commands explanations I'm not done yet on testing them so give me some time and they should be fixed by today 😉 .
